/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'placed' : IDL.Null,
  'completed' : IDL.Null,
});
export const Platform = IDL.Variant({
  'pc' : IDL.Null,
  'xbox' : IDL.Null,
  'playstation' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'listingId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'platform' : Platform,
  'seller' : IDL.Principal,
  'buyer' : IDL.Principal,
  'price' : IDL.Nat,
});
export const Stats = IDL.Record({
  'wins' : IDL.Nat,
  'level' : IDL.Nat,
  'kdRatio' : IDL.Float64,
});
export const ListingStatus = IDL.Variant({
  'active' : IDL.Null,
  'sold' : IDL.Null,
});
export const Listing = IDL.Record({
  'id' : IDL.Nat,
  'status' : ListingStatus,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'rank' : IDL.Text,
  'description' : IDL.Text,
  'platform' : Platform,
  'seller' : IDL.Principal,
  'prestige' : IDL.Nat,
  'stats' : Stats,
  'price' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], []),
  'createListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Platform,
        IDL.Text,
        IDL.Nat,
        Stats,
        IDL.Nat,
        IDL.Vec(IDL.Text),
      ],
      [Listing],
      [],
    ),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActiveListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'listBuyerOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listSellerOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'placeOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], []),
  'removeListing' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'updateListing' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        Platform,
        IDL.Text,
        IDL.Nat,
        Stats,
        IDL.Nat,
        IDL.Vec(IDL.Text),
      ],
      [IDL.Opt(Listing)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'placed' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Platform = IDL.Variant({
    'pc' : IDL.Null,
    'xbox' : IDL.Null,
    'playstation' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'listingId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'platform' : Platform,
    'seller' : IDL.Principal,
    'buyer' : IDL.Principal,
    'price' : IDL.Nat,
  });
  const Stats = IDL.Record({
    'wins' : IDL.Nat,
    'level' : IDL.Nat,
    'kdRatio' : IDL.Float64,
  });
  const ListingStatus = IDL.Variant({ 'active' : IDL.Null, 'sold' : IDL.Null });
  const Listing = IDL.Record({
    'id' : IDL.Nat,
    'status' : ListingStatus,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'rank' : IDL.Text,
    'description' : IDL.Text,
    'platform' : Platform,
    'seller' : IDL.Principal,
    'prestige' : IDL.Nat,
    'stats' : Stats,
    'price' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], []),
    'createListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Platform,
          IDL.Text,
          IDL.Nat,
          Stats,
          IDL.Nat,
          IDL.Vec(IDL.Text),
        ],
        [Listing],
        [],
      ),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActiveListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'listBuyerOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listSellerOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'placeOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], []),
    'removeListing' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'updateListing' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          Platform,
          IDL.Text,
          IDL.Nat,
          Stats,
          IDL.Nat,
          IDL.Vec(IDL.Text),
        ],
        [IDL.Opt(Listing)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };